adblock: false
auto_continue: true
command: ''
command_before_end: ''
custom_ip: 0.0.0.0
days_between_db_retest: 1
db_type: json
debug: false
dns_server:
- 1.1.1.1
- 1.0.0.1
filter: ''
generate_complements: false
generate_hosts: true
generate_json: false
header_printed: false
hierarchical_sorting: false
http_codes:
    active: true
    list:
        potentially_down:
        - 400
        - 402
        - 403
        - 404
        - 409
        - 410
        - 412
        - 414
        - 415
        - 416
        potentially_up:
        - 0
        - 300
        - 301
        - 302
        - 303
        - 304
        - 305
        - 307
        - 403
        - 405
        - 406
        - 407
        - 408
        - 411
        - 413
        - 417
        - 500
        - 501
        - 502
        - 503
        - 504
        - 505
        up:
        - 100
        - 101
        - 200
        - 201
        - 202
        - 203
        - 204
        - 205
        - 206
iana_whois_server: whois.iana.org
idna_conversion: true
inactive_database: true
less: false
links:
    api_date_format: https://pyfunceble.funilrys.com/api/date-format
    api_no_referer: https://pyfunceble.funilrys.com/api/no-referer
    config: https://raw.githubusercontent.com/funilrys/PyFunceble/dev/.PyFunceble_production.yaml
    dir_structure: https://raw.githubusercontent.com/funilrys/PyFunceble/dev/dir_structure_production.json
    iana: https://raw.githubusercontent.com/funilrys/PyFunceble/dev/iana-domains-db.json
    mariadb: https://raw.githubusercontent.com/funilrys/PyFunceble/dev/db_types/mariadb.sql
    mysql: https://raw.githubusercontent.com/funilrys/PyFunceble/dev/db_types/mysql.sql
    psl: https://raw.githubusercontent.com/funilrys/PyFunceble/dev/public-suffix.json
    repo: https://github.com/funilrys/PyFunceble
    requirements: https://raw.githubusercontent.com/funilrys/PyFunceble/dev/requirements.txt
    sqlite: https://raw.githubusercontent.com/funilrys/PyFunceble/dev/db_types/sqlite.sql
local: false
logs: true
maximal_processes: 25
mining: false
multiprocess: false
no_files: false
no_special: false
no_whois: false
outputs:
    analytic:
        directories:
            parent: Analytic
            potentially_down: POTENTIALLY_INACTIVE
            potentially_up: POTENTIALLY_ACTIVE
            suspicious: SUSPICIOUS
            up: ACTIVE
        filenames:
            potentially_down: down_or_potentially_down
            potentially_up: potentially_up
            suspicious: suspicious_and_merged_in_results
            up: active_and_merged_in_results
    complements:
        directory: complements
    db_type:
        directory: db_types
        files:
            mariadb: mariadb.sql
            mysql: mysql.sql
            sqlite: sqlite.sql
    default_files:
        dir_structure: dir_structure.json
        iana: iana-domains-db.json
        inactive_db: inactive_db.json
        mining: mining.json
        public_suffix: public-suffix.json
        results: results.txt
        sqlite: pyfunceble.db
        whois_db: whois_db.json
    domains:
        directory: domains
        filename: list
    hosts:
        directory: hosts
        filename: hosts
        ip_filename: ips
    json:
        directory: json
        filename: dump.json
    logs:
        directories:
            parent: logs
            percentage: percentage
        filenames:
            auto_continue: continue.json
            date_format: date_format.json
            execution_time: execution_time.json
            no_referer: no_referer.json
            percentage: percentage.txt
            whois: whois.json
    parent_directory: output/
    splited:
        directory: splited
plain_list_domain: true
quiet: true
seconds_before_http_timeout: 6
share_logs: true
show_execution_time: false
show_percentage: true
simple: false
split: false
status:
    list:
        down:
        - down
        - inactive
        - error
        generic:
        - generic
        http_active:
        - http_active
        invalid:
        - ouch
        - invalid
        potentially_down:
        - potentially_down
        - potentially_inactive
        potentially_up:
        - potentially_up
        - potentially_active
        suspicious:
        - strange
        - suspicious
        - hum
        up:
        - up
        - active
        valid:
        - valid
        - syntax_valid
        - valid_syntax
    official:
        down: INACTIVE
        invalid: INVALID
        up: ACTIVE
        valid: VALID
syntax: false
travis: true
travis_autosave_commit: '[Autosave] Testing for Ultimate Hosts Blacklist'
travis_autosave_final_commit: '[Results] Testing for Ultimate Hosts Blacklist'
travis_autosave_minutes: 10
travis_branch: master
unified: false
user_agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko)
    Chrome/73.0.3683.86 Safari/537.36
verify_ssl_certificate: false
whois_database: true
