env:
  global:
    - secure: c9/O+suTkehdQkvg2yaBFX+M5qI4wDdeAvil7eeGtk2ico1R0JZpZWlWsB4Wl30j86oFTw6V47dL7Vrdy227PG4dbq3l7R9eeOmb4sQjhJHHSc3Kno1Z8Ju4z+iaGGHYW8oudOpUXnsA6a+ZI1s+oc+0b6tEHyGUdBjbKgVSr/+q2D4XvokvEtJXE3d4/ZQpVWuPtf+4R8qlXw8ApDka+S05DdBZ/OtcJISGWqnLYbSuBFvNzzNJKh2imViLAFUFXlAfcUZCwT8qFP3A/jYA3BQ6TBdy6P/SCAZOUeKBanj1ODlAuu586ENCbK7iSTaWQCHag/qq5R3POYKy8SIfVkysadmR67tVeYNRxJzpxnQMOk8Elnu6ADKLgm2zXseyPL+BJomMvTLrLTA9ED2SYVKApsn+iMccXDsDabjhMNNQLcPHisGUvRlrqzFh1XHTCElAlcG7vhcfcyYeaU1mShAKW2Dcb/UGKJ81j1rEXtQ0QrJxtZ0mWqA2tK5gYVFITB5zq+2wS7Q+3E2hUx5e4vM9yl1ZN69sa2Jso3gkCa9GH5OuRQSLJR7Vu1g0nSwA3wgfzyDm+jRqh7ZAd099MrpeZU0wYpK2ggeRr7ND1HexNO+vT+f/zTEL2mTBSHgB3gpePxLf4fHUJNZVco7HZGryuy9oekmo+Mx6Hzdamk8=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/MalwareDomainList.com
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
