env:
  global:
    - secure: WQJ4coCHBD/0JjbaHARpdGVBZV52qgMeGPO28O9pJiMace38o9USBrkFfM8YofyJqhnqxIdDDwh+Q79GfT3XXk1LtDiHd9yojI/k6Yi8qRynwbZxudDPcGZg6lgKIfFZysSvRLSZPv9isyE15uV8lAv/LoEdH/Zr0AAMDiQbcoMVniBl7jBfjPeugGaNws22rSt8O0Bhj0vbOOxaZfaUtgT4dhoLnvW+x5VrCWoyx889Ze3uTGdgWqPn2GPO37A8WWaeZc08Pkh8vHHRHG+Z9C/EQMCKaQKjt5/45bqy6fLnXIGUGw/Ub81vMag07hrgX2ijC7XWIGzVwvkp+4Bl+yXfDLMt8BzUf3e/8uEUdEVmTya6ylZg+2pBIYB6fFRiDRRbVVUzz360VIX0EFr2QYeDSXfdXq6hfiptYptzrrJBFTdLm1kY6GMftsP6n7kk5zLmqiXTdgcTHZaANgFY54i327hWsTK8W9fSxg4DuHnZ/UX5hzPyVn8hZmArxlTnfYz+LAt8DDqxNwkfRwInBl0cthwy2tDS1Ptv4ABrhdlUgxf3T+1FikTBPvRHrELT8A2LddSWBDSj1IsRMZ+y+Weas3JrEdQ29S6zZAMnUvn4+ijygPomVwFFqNFv81MIpKpWnVqVZbd+X8w38q2lOgW8WIHA3evmyJ9muR2eMqs=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: mitchellkrog@gmail.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/MalwareDomainList.com
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

before_install:
  - sudo apt-get -y install python3-pip python3-yaml
  - sudo apt-get -y install dos2unix
  - pip3 install colorama

script:
  - python3 ./update.py

notifications:
  email: false
