env:
  global:
    - secure: GKx8YvRgJOU3awzcORGd5SBWctJXZ1stNCJZM/5FHDXEdvE0+tIJYGGa3miRhvTW5Zig6JUdltErtsiZP52W7FCFZYg3bio2kSPe8Mq5qjuQwgfOLFhAa0lJv1uQirIsVqrmSbWSsl7oAKXRO8AdViVldoiuRlYBfSsTvkC19njI99jCRJwnxS+jOtfu2yVKAJrI6CYWyncrShxVE3axW1re0bT90b8S6MXVd+MdyBr/PpuAeinqPOLLeYPXK66bu2LoaP4FmDR21tCJtbAqt8mhQ/25yIhz8EGZlYvo8jJv8poAwGMSFM6xnmjiol59VdxSLBcH+wXCHrX3ovvmwjurJ5QCqV1SanqYZxKN9zp0Nk0vvZ6bB4bYUg2BzizW5TPbMCp1Rm3QHH1wgD1XpJBiiCWVkOg1hqxkVxsfC/Kfn2QPJyJBAGj8rrzIUq9kMADRI+Icl3np4uy2r6X51PFeS4OWsbcd2f8nWFGBw+VD463hUM7YOTrDcQiDqRlFEn7sckt3dIE3+7+GDYl7OiHlTumti2t4aEVL0IA4ama+n0tVdxIZhVIPE1w7dSVA3fVe95ULrnKAtgcedvfNDoynfpYtK+bx7Xvma4OsAJXVrvaJ/ABaJHVGKWUkPKrCell8J9PEf2kDbZ33HyWPf0RGem3bhfFBPDqzwxL4rzM=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/MalwareDomainList.com
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
