env:
  global:
    - secure: Vc9NhmeMxUEVXDDfdWNziFvoSk94mgQPLEri+FP6D+dOdLFmfKN+KunsIamVjFPsdtwYwe9NCw9ipbxIBUDP5vY+Xw2mlfHdDrYozQBhRmG1r5DIZhzgmVCqyMDI8EVlojo+T1HmmCyD1+JojjkjnbJhUzVyY9mMdgp4YRokcgajDzC0l3JtXC3U4RshsZiJ+Qqt5/lZqoR0PGU+rNqGvTveGG4IUdPghfI6hH1HWg3VbEdlbR6SGA7t8qLv31t8czWVPRolGt7dkU4uZoW5Lc7tN20DI1r1bIhPPX6DrCMGppPz9de2h3NNhccUG4N45D7bDdd0g3GpOWNmlEplQ0FJF24bmPz3Y9WLYxgYvud51Px+S/x8tpnSB8JaywrqdnoMeSindx5z97b5zAVvL2+HAB6Elv9wZjx6BelWA4/OfQN6ju0ZY7vmFnxC5wR6v3CnSMHx/RAQgQU1KUt+v0q3ZIRDZa4W1S7Chdrx+2Td4Z0KV+7RfhF6uiOHWPRTzvR3IGvJMtkDQ5yIGhz/q5FbvD9r6yIZNLHMuWSR0IaauvLpSSlfM1e7A3vMHrCW99xo0mnAjED+VXNF5EVxxxPum5m7bGFWsygMhTXAAem/bp5Jpos2arjcbU8GGA0BjZv8Swj2BkRzttbdoPztaSOD7Tt/vncvaTNVBGEwgI4=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/MalwareDomainList.com
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

before_install:
  - pip3 install colorama
  - sudo apt-get -y install dos2unix

script:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble && python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
