env:
  global:
    - secure: GgAgq3MCtmYPROWTjhmbwcM12jIMtI9GwreZ6o964mBOdfngpZ2OmKvBarpuqhCjrAnpJFxQh3/bM6HOFlRPRthVI7lgWVMFmwsMo8KRrrYf/bZkQRi2V1Y7mI8vfchVwxZdl+s566DZ0WGv0nrIuXz2Etr9y5WJNwt9MvQJ/8J88PX7Yu6VY38finxrXkuPqhwaWjXMDI9e2WNmlC/QiTXhgjIfeaKELYDSU/TciSZVwQiLSwiObPHkcI0MkgGkRfxRmpInxjT47VrFCOt+Arp4db3x1/YoObdwLlB2oSPEzSWk1Yd3isvgsnzF5gjZlJztxkEcH7HCxlvSMvCtlwMJ4tOBGmmtMV7ThS4tAhsN6t1CAzNB2oWTAjRQ03BnllTiEJvLdCmvnkNZFpl9ljbr4oo22mCH+vrTTsTlZWZEWkN2WoxrhPY4Ffz/TkG1TW1gjn9uLc8hiv/VgZ+te6H5LkWPgOkhnR49dBUqYSA9+8uVGCFZj08C+SQhgPMFMaVpE2HtIUO2m13TeuMaJgQaCM5C18A9B0+ACJOLTTCXtEwLiynDUP6KqyoSh9JSsVJtMJxowV7S2nmkXmyFXdYPRp22wqqD63wnPlIlpFH+DUVaGODEBn9IElmdKcGkx5JqafXK71yIrfcQqhpoB8DWezCsA4MJD/RwLAuoggs=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/MalwareDomainList.com
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
