env:
  global:
    - secure: A+8avWfIhfHS+mn2Jig9b+fQW+6irAbZnrfykqJJ3TjkQOxzpFUkWpNrbbPQAT9f8+lpdiSub2GTp4uGQwgjXzfEnYMR1DojfqMLMtdZxUw1viAAT+jxoAeqsMb32H7JkLNxMH5vQ+JghW/TN3DCjlrtLEwkn3WBZmq1wK9U2gE3GqRMhNlDFrLfs0qn6T7Zs87cRVI932Vfe2dQXrRY9xFDxLemYolAcns9eH+6htPxmlYjKOHFIzYWVxOzPr8cyND+6wP9QzcTRiGNGggEls/JKZ5phsbniiE3tD7cqkykbCRpPDSEyhn9xc5Zp6ZuJ05P4PFje/phYs3JD2RXxfSAj2xqCFw9fItlgVHXllnMekp1eOPQKDM95JAwFdh6FywIjZkgenUIgAui/icS6lmH5M+hTcGJaVMTdDtJ4Rz/8Ai8bUUK9eEVyA/CVUHU8Ankx7hgtimySJlLPnId5/V94bBn6EDD8rQOWb+LAhJAKaWCUc9nYBc2dOPA9NzxqEVoD0yBVpClli3MDyO4n6V42zVS3pKUm3MFCMBJp+COQO/IG45VWc0aDmJwD/7Z1c553tsJHEDeJg+xA59e9Yuj7+bFCQVhryRtAkLLMiJ7plyYHGRy5l5rpkPzP9138pA3NdWxf8dzFfmwn9wiqhP8y6J3XIjuPEi+yDbBqs0=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/MalwareDomainList.com
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

before_install:
  - pip3 install colorama
  - sudo apt-get -y install dos2unix

script:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble && python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
