env:
  global:
    - secure: XXL7aQsQdRbk+oSrM3RHs+n4sm4OfhaamaiPrwcyP5k4bsWxGc7BGjLhvAsLGTT0vaW07ACmqY0VCDRTWHadjLbF67ArsV/0lmXwuesOXn+cogznQOW9L8bndPIqx6hZAnB1BwyyOfR2Z6jdg3YEis1RKlAO+NfR6TP14JNiNTPH8PDk4BTJkCZFL4VsHcVsNeDNaBH703PDGowBSd1NokyEU60cYhJ7GRInU7T+tVwjo2Cg9PoxKG8pWtUv1KPdpa6ZYPxeQ7Yzwm9mGgI2s+3GM+djxyhlMHgwLWJYl6ZwtT36Ed+ojD0BwWJQHO/1i8Nt6PD7/cYmSPlafF1lahyMmwfH7om97PjSTOcwKylEot2G+tjzj4Q67uAYC0wntgKdNkqvEpBNyf+SsHwXbZfEYKd53gxHHOZawKhkGxM+EVu66qsypgveAo7YIOBMlxb+HLyZESGFA924PgIUjDhAab1rl5ANhiWPKAi9IJyDhMlIpqchWZj5pgVUtF8taE01KiI0JZDiXxlbBmCSdeZLNsDn1q6kxgEOFjsVkLfF9eef63iaVl9OcUh7LO7+lmAbFhieQxutZ7jAKdOmFrLtff3oTA03psjPzOD7QPrp9quDkKDr35ZO77uMrGmCbzFSZcI7u/V62/KbRZluB3I2KHjc5F5gldk+j5A9Vqg=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/MalwareDomainList.com
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
