env:
  global:
    - secure: SfOJjSi3Q9Xkuf/1eRE1WjBWJwfL1BkBTaDDvOEztJK3k17YLOe4eIDMrH48jLqvXYgvFGjqwoqoGhecP38RgirmxNFqXtmedGyy0nZem0t4BhkqsVFWOKk8yls+3aUj2tQMrlrcDTHAQPIJ/Bdu+e7d8ac9QrPUkkla7esM/jDyAwhFSlEEXVBK/4rpMeVIaasAHiMpK72QL9ENTYFNUZc4UrPHp+UWFUSy4FgkRGNKIcvuMjsHMFtdSZP4oTEyvwe67i+50qBD6YEqnSJOWy0q0qdGwJxKPTtP4/3hjur9UqLJk+aPdjJx+9tvT87dG71/nQ0yAa/afJDAATdkrkCNKw+2LLv46PuikTKCAhbr9fUgvCGdwKp3HUThtCj/FSDV2oMpT5YvYfTKX8APdTOgm1ZYWvCKpPap2UubZZXSXj27PG3PbFqtqXZOavKqQiJNPFPDsiv+4hy8bnkyyY3DiVnq7sXc0+9r0wlOI62eQFdo2vWPOl2DDo6Hm3t3sk+VzFgsyiJ++9DJ4SgAn3ErI9JmcXE/Z5bvOSGDQxkyAg1mpmRmgFz9rb22JfLl5Ogq3vHOexfkdmm2YMqeG+qeEjl2HFICd4t/TAJaSfDfXoqdkji9PRRzRj20JM98guM+O4oI5znyZ50DYNUgDzFyRjFHaR9vaf7y+Zr8F5Y=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/MalwareDomainList.com
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
